FROM golang:1.18

LABEL MAINTAINER=shengchaohua1995@gmail.com

COPY .. /src
WORKDIR /src

RUN make

EXPOSE 8010

ENTRYPOINT ["./bin/red-packet-backend-admin", "-port=8010"]

# docker build -t red_packet_backend_admin:v1.0
