[admin]
    env = "test"
    addr = "127.0.0.1:10000"
    log = "./log/admin_server.log"

[api]
    env = "test"
    addr = "127.0.0.1:11000"
    log = "./log/api_server.log"

[main_db]
    [[main_db.db]]
        host = "127.0.0.1"
        port = "3306"
        user = "root"
        password = ""
        db_name = "red_packet_main_test_db"
        db_max_open_conns = 100
        db_max_idle_conns = 100
        db_max_life_time = 3600
        db_show_sql = true
        db_is_master = true
    [[main_db.db]]
        host = "127.0.0.1"
        port = "3306"
        user = "root"
        password = ""
        db_name = "red_packet_main_test_db"
        db_max_open_conns = 100
        db_max_idle_conns = 100
        db_max_life_time = 3600
        db_show_sql = true
        db_is_master = false
