[main_db]
    [[main_db.db]]
        host = "127.0.0.1"
        port = "6606"
        user = "root"
        password = "123456"
        allow_native_passwords = true
        db_name = "red_packet_main_db"
        db_max_open_conns = 100
        db_max_idle_conns = 100
        db_max_life_time = 3600
        db_show_sql = true
        db_is_master = true
    [[main_db.db]]
        host = "127.0.0.1"
        port = "6607"
        user = "root"
        password = "123456"
        allow_native_passwords = true
        db_name = "red_packet_main_db"
        db_max_open_conns = 100
        db_max_idle_conns = 100
        db_max_life_time = 3600
        db_show_sql = true
        db_is_master = false

[server]
    env = "dev"
    port = "10000"
    log_file = "./log/admin.log"
    role = "admin"
